version: "3.9"
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"

  project-service:
    build: ./project-service
    ports:
      - "8082:8082"

  task-service:
    build: ./task-service
    ports:
      - "8083:8083"

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - project-service
      - task-service
      - notification-service

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway
