server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: 12345678901234567890123456789012
    expiration: 86400000
